
---
- hosts: servers
  remote_user: root


  tasks:
              
    - name: create apache user
      user: name= "apache"

    - name: Copy template
      template: src="anagrams.j2"
                dest="/var/www/html/index.php" owner=apache group=apache

    - name: Restart apache2
      service:
        name: apache2
        state: restarted

