---
- hosts: servers
  remote_user: root
  
  tasks:
    - name: Install Apache
      apt: name=apache2 update_cache=yes state=latest

    - name: Install php
      apt: name=php update_cache=yes state=latest

    - name: Make sure Apache is working
      service: name=apache2 state=started

    - name: Stat of one update
      stat: path=/root/update-done
      register: update_stat

    - name: Update
      apt: name=* state=latest
      when: update_stat.stat.exists == False

    - name: Register for only one update
      shell: "echo done > /root/update-done"
      when: update_stat.stat.exists == False



